### ISSUE TITLE
Token list and token profile should better resemble mockups 

### ISSUE THREAD

**Issue by jamslevy** [taptrust/taptrust#5]
![screen shot 2017-12-20 at 11 47 27 pm](https://user-images.githubusercontent.com/17043/34245910-24b1be7e-e5e1-11e7-8ce3-273defaa102d.png)

![screen shot 2017-12-20 at 11 47 43 pm](https://user-images.githubusercontent.com/17043/34245922-2a37d7ca-e5e1-11e7-8a21-5342a6a63a97.png)

- Each of the following fields should be updated to resemble the mockups: age, score, number of reviews, trusted badge, category,
- Improve font family

**Comment by jamslevy** [comment]
![taptrust mockups v1](https://user-images.githubusercontent.com/17043/36287854-4f5133f0-126c-11e8-9853-8a1ed1be4572.png)


Note the mockups were specific to a mobile app so not all features are being immediately implemented, this is more of a general style reference.

**Comment by papistan** [comment]
I've addressed the trusted badge, font, grey line, category capitalization issues. Need permission to push branch then will address remaining issues

**Comment by jamslevy** [comment]
Closing and opening more specific tickets.
